export const PRIVATE_ROUTES = [
  {
    path: `/`,
    key: 'landing-page',
    label: 'Landing Page',
    element: 'LandingPage',
    showInSidebar: false,
  },
  {
    path: `/products`,
    key: 'products-page',
    label: 'Products',
    element: 'ProductsPage',
    showInSidebar: false,
  },
  {
    path: `/products/:id`,
    key: 'product-details-page',
    label: 'Product Details',
    element: 'ProductDetailsPage',
    showInSidebar: false,
  },
  {
    path: `/products/compare`,
    key: 'compare-page',
    label: 'Compare Products',
    element: 'ComparePage',
    showInSidebar: false,
  },
  {
    path: `/contact`,
    key: 'contact-page',
    label: 'Contact Us',
    element: 'ContactPage',
    showInSidebar: false,
  },
  {
    path: `/terms-and-conditions`,
    key: 'terms-and-conditions-page',
    label: 'Terms and Conditions',
    element: 'TermsAndConditionsPage',
    showInSidebar: false,
  },
  {
    path: `/services`,
    key: 'services-page',
    label: 'Services',
    element: 'ServicesPage',
    showInSidebar: false,
  },
  {
    path: `/projects`,
    key: 'projects-page',
    label: 'Projects',
    element: 'ProjectsPage',
    showInSidebar: false,
  },
  {
    path: `/projects/:id`,
    key: 'project-details-page',
    label: 'Project Details',
    element: 'ProjectDetailsPage',
    showInSidebar: false,
  },
  {
    path: `/blogs`,
    key: 'blogs-page',
    label: 'Blogs',
    element: 'BlogsPage',
    showInSidebar: false,
  },
  {
    path: `/blogs/:id`,
    key: 'blog-details-page',
    label: 'Blog Details',
    element: 'BlogDetailsPage',
    showInSidebar: false,
  },
  {
    path: `/about-us`,
    key: 'about-us-page',
    label: 'About Us',
    element: 'AboutUsPage',
    showInSidebar: false,
  },
  {
    path: `/careers`,
    key: 'careers-page',
    label: 'Careers',
    element: 'CareersPage',
    showInSidebar: false,
  },
  {
    path: `/careers/job/:id`,
    key: 'job-details-page',
    label: 'Job Details',
    element: 'JobDetailsPage',
    showInSidebar: false,
  },
];
